/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "iotProjekt.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(iot_IoTMessage, iot_IoTMessage, AUTO)


PB_BIND(iot_BME680Data, iot_BME680Data, AUTO)


PB_BIND(iot_HCSR04Data, iot_HCSR04Data, AUTO)





